version: "3.7"

services:
  bankingHolderMicroService:
    image: yngviwarrior/banking-holder-ms:server
    container_name: banking-holder-ms
    ports:
      - "3001:3001"
    restart: always
    # logging:
      # driver: none
    networks:
      - banking-network
    depends_on:
    - bankingDB
  bankingAccountMicroService:
    image: yngviwarrior/banking-account-ms:server
    container_name: banking-account-ms
    ports:
      - "3002:3002"
    restart: always
    # logging:
      # driver: none
    networks:
      - banking-network
    depends_on:
    - bankingDB
  bankingDB:
    image: mysql
    restart: always
    # logging:
      # driver: none
    container_name: bankingDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - data:/var/lib/mysql
    networks:
      - banking-network

volumes:
  data:

networks:
  banking-network:
    driver: bridge
