version: "3.7"

services:
  bankingAPI:
    image: yngviwarrior/bankingAPI:server
    container_name: bankingAPI
    ports:
      - "3001:3001"
    restart: always
    logging:
      driver: none
    networks:
      - bankingAPI_network
    depends_on:
    - db
  db:
    image: mysql
    restart: always
    logging:
      driver: none
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'XE3kNWeGffTQHb'
      MYSQL_USER: 'igor'
      MYSQL_PASS: '123456'
    volumes:
      - data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - bankingAPI_network

volumes:
  data:

networks:
  bankingAPI_network:
    driver: bridge
