package infra

var TAREFAS_ID_TIPO_SEND_EMAIL int64 = 1
var TAREFAS_ID_TIPO_GAME_STATUS int64 = 2
var TAREFAS_ID_TIPO_GAME_STATUS2 int64 = 3
var TAREFAS_ID_STATUS_PENDENTE int64 = 1
var TAREFAS_ID_STATUS_COMPLETO int64 = 2
var TAREFAS_ID_STATUS_CANCELADO int64 = 3
var TAREFAS_ID_STATUS_RESERVADO int64 = 4

var MODELO_USUARIO_NOVO_CADASTRO int64 = 1
var MODELO_USUARIO_RECUPERAR_SENHA int64 = 2
var MODELO_USUARIO_AVISO_ALTERACAO_SENHA int64 = 3
var MODELO_USUARIO_RECEBIMENTO_BITCON_0_CONFIRMACAO int64 = 4
var MODELO_USUARIO_RECEBIMENTO_BITCON_1_CONFIRMACAO int64 = 5
var MODELO_USUARIO_CONFIRMAR_SAQUE_BITCOIN int64 = 6
var MODELO_USUARIO_SAQUE_BITCOIN_CONFIRMADO int64 = 7
var MODELO_USUARIO_SAQUE_BITCOIN_ENVIADO int64 = 8
var MODELO_USUARIO_AVISO_ALTERACAO_SENHA_SAQUE int64 = 9
var MODELO_USUARIO_AVISO_CONTA_EM_ANALISE int64 = 10
var MODELO_USUARIO_ENVIO_INTERNAL_2FA_TOKEN int64 = 11
var MODELO_USUARIO_EMAIL_CONFIRMATION int64 = 12
var MODELO_USUARIO_EMAIL_VERIFIED_CONFIRMATION int64 = 13
var MODELO_USUARIO_EMAIL_1_AFTER_EMAIL_VERIFIED_CONFIRMATION int64 = 14
var MODELO_USUARIO_EMAIL_2_AFTER_EMAIL_VERIFIED_CONFIRMATION int64 = 15
var MODELO_USUARIO_EMAIL_MARKETING_DEPOSIT int64 = 16
